export const SOLUTIONS = [
  {
    step: "01",
    title: "Campaign Setup",
    tagline: "Traffic it once, correctly",
    description: "Creatives, destination URLs, and tracking tags are entered into one structured form, that's fed straight into QA rather than a separate spreadsheet.",
    expanded: "Every field maps directly to what the QA validator checks next, so nothing gets re-typed or re-copied between tools.",
    color: "campaign-red",
    mockup: "setup",
  },
  {
    step: "02",
    title: "QA Validator",
    tagline: "Every check, automated",
    description: "Links, tracking tags, UTM params, and creative specs are validated automatically against your rules before a campaign is ever cleared to launch.",
    expanded: "Checks run in seconds: HTTP status on every URL, regex validation on UTM and tag syntax, and file-size/dimension checks against your creative spec sheet.",
    color: "campaign-blue",
    mockup: "checklist",
  },
  {
    step: "03",
    title: "SLA Tickets",
    tagline: "Nothing sits unanswered",
    description: "Support requests are linked to the campaign they affect, with a visible SLA timer so nothing gets buried in a Slack thread or inbox.",
    expanded: "Priority sets the clock automatically, high-priority issues get a 2-hour window, standard requests get 4 hours, so nothing quietly slips.",
    color: "campaign-pink",
    mockup: "ticket",
  },
  {
    step: "04",
    title: "Escalation Log",
    tagline: "A trail, not a memory",
    description: "When an issue needs another team, it's routed with a timestamp, reason, and owner, so there's always a record of who handled what.",
    expanded: "Every handoff is timestamped and reasoned, searchable later when a client asks why something took as long as it did.",
    color: "campaign-yellow",
    mockup: "escalation",
  },
  {
    step: "05",
    title: "Dashboard",
    tagline: "The health of the desk, at a glance",
    description: "QA pass rates, SLA response times, and open escalations roll up into one view, the same numbers a team lead needs to run standup.",
    expanded: "Filter by campaign type, date range, or team member, the same view whether you're checking one campaign or the whole desk's week.",
    color: "campaign-mint",
    mockup: "dashboard",
  },
];